---
- name: Print OS Version for Windows
  hosts: windows_servers
  gather_facts: false  # We don't need to gather facts in this case
  environment:
    ANSIBLE_REMOTE_TEMP: C:\ansible_temp
  tasks:

    - name: Ping the hosts
      ping:
