---
- name: Print OS Version
  hosts: your_target_group
  gather_facts: true  # This gathers facts about the remote hosts, including OS information

  tasks:
    - name: Display OS Version
      debug:
        var: ansible_facts['distribution'] + " " + ansible_facts['distribution_version']
